# Generated by Django 5.0 on 2023-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField()),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattagram', 'Chattagram'), ('Sylhet', 'Sylhet'), ('Rongpur', 'Rongpur'), ('Rajshahi', 'Rajshahi')], max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('filedoc', models.FileField(upload_to='filedoc')),
            ],
        ),
    ]
